[package]
name = "benchmarks"
version.workspace = true
edition.workspace = true

[[bench]]
name = "cmd_instantiate_async"
harness = false
path = "benches/commands/instantiate_async.rs"

[[bench]]
name = "benchmark"
harness = false

[[bench]]
name = "call_async_with_host"
harness = false

[[bench]]
name = "call_async_with_pooling_alloc_host"
harness = false

[[bench]]
name = "call_async_with_pooling_alloc"
harness = false

[[bench]]
name = "call_async"
harness = false

[[bench]]
name = "call_with_pooling_alloc_host"
harness = false

[[bench]]
name = "call_with_pooling_alloc"
harness = false

[[bench]]
name = "call"
harness = false

[[bench]]
name = "instantiate"
harness = false

[[bench]]
name = "instantiate_async_with_pooling_alloc_host"
harness = false

[[bench]]
name = "instantiate_async"
harness = false

[[bench]]
name = "instantiate_async_with_host"
harness = false

[dependencies]
anyhow.workspace = true
engine.workspace = true
testdata = { path = "../testdata" }
v21host.workspace = true
v21ahost.workspace = true
v41host.workspace = true
v41ahost.workspace = true
tokio.workspace = true

[dev-dependencies]
golden.workspace = true

[dev-dependencies.criterion]
features = ["async_futures", "async_tokio"]
workspace = true
