[package]
name = "pulldown-cmark-cmd"
version.workspace = true
edition.workspace = true

[dependencies]
pulldown-cmark = { version = "0.13", default-features = false, features = ["html"] }
anyhow.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wit-bindgen.workspace = true

[lib]
name = "pulldown_cmark_reactor"
crate-type = ["cdylib"]
bench = false
